name: Nightly Smoketest for Lucille Distributed Mode

on:
  schedule:
    # runs at 00:00 UTC every day, 20:00 EST
    - cron: '0 0 * * *'
  workflow_dispatch:  # allows manual triggering of the workflow via actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up Docker Compose Location
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./lucille-examples/lucille-distributed-example/docker-compose.yml"
      - name: Run Maven Verify with Nightly Profile
        run: mvn verify -Pnightly --file pom.xml