name: Scan code with Snyk

on:
  workflow_dispatch:
        inputs:
          language:
            description: 'Code language to scan'
            required: false

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Snyk CLI to check for security issues
        # Upload the SAST issues to GitHub Code Scanning
        uses: snyk/actions/maven-3-jdk-21@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          ORGANIZATION: 88b31041-9487-4fb4-a9b3-9c643940d52e
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Snyk version
        run: snyk version

#      - name: Authorize Snyk
#        run: snyk auth ${{ secrets.SNYK_TOKEN }} -d

        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
#      - name: Snyk Code test
#        run: snyk code test --sarif |& tee snyk-code.sarif || true

        # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
